### ISSUE TITLE
update_salinity_mapping crash when insufficient unique CTD data

### ISSUE THREAD

**Issue by jlovellcsiro** [ArgoDMQC/matlab_owc#12]
OWC crashed when update_salinity_mapping called noise.m when using CTD reference data for a float in the Southern Ocean (1901751). It turned out to be a problem in screening the selection of data to pass to noise.m where the test for sufficient reference data was not specific enough due to probable duplicate CTD references at the same location. CTD reference data being used is CTD_for_DMQC_2021V02.

We implemented a fix by testing for uniqueness in location but this is probably not the ideal solution.
This is the code segment inserted in update_salinity_mapping near line 260:

--
	    % PO: System will crash calling noise, below, if all profiles are at the same location
	    number_of_unique_latitudes   = length(unique(la_hist_lat));
	    number_of_unique_longitudes  = length(unique(la_hist_long));
	    number_of_unique_profiles    = number_of_unique_latitudes * number_of_unique_longitudes;
	    if length(la_hist_sal)>5 & number_of_unique_profiles==1;
		    display('PO: Climatology includes all duplicates');
	    end;
            % map historical data to float profiles -------------------------
            %if( length(la_hist_sal)>1 ) % only proceed with mapping if there are more than one data point 
            %  change config 129 -> at least 5 points are required   
	    %
	    % PO: This test should be changed to test how many unique profiles are available
	    %
            %PO if( length(la_hist_sal)>5) % only proceed with mapping if there are more than five data point
            if( length(la_hist_sal)>5 & number_of_unique_profiles>1) % only proceed with mapping if there are
		                                                     % more than five data point ...
								     % (PO) and if there are more tham one unique location
--

@cabanesc and Annie Wong (@apswong) joined the discussion and Annie suggested to use something like the following:
> if( length(la_hist_sal)>5 )

perhaps change it to something like:

> if( length(unique(la_hist_long))> 5 & length(unique(la_hist_lat))>5 & length(unique(la_hist_dates))>5 )

--
I implemented this and the code was able to run, but the mapped salinity is different from the previous method.
An image of la_mapped_salinity for each of the methods is shown here:
![OWC_mappedSal_compare](https://github.com/ArgoDMQC/matlab_owc/assets/32728336/22bee166-d11f-49bc-8150-dbfa8a08803d)

There is less data mapped in the 'Annie' version than the 'Peter' version. [Note also there seems to be some strange (reversed order?) data in cycle 15]
The simple uniqueness test above is flawed in logic since it treats lon, lat and date independently, when they should actually be 'triplets'. However, I would have thought in practice it would work. This needs some more thought and discussion.

**Comment by cabanesc** [comment]
From discussions with Annie:

- more than one historical salinity profile with unique position (lat,lon) is required for noise.m. We should test for uniqueness in position only, without dates, as the function noise.m crashes as long as (lat,lon) is unique - e.g . mooring data

and
- more than five historical salinity profiles are required to produce realistic mapping error estimates

The following new IF statement replaces the previous one (i.e.  length(la_hist_sal) > 5) :

if( (length(unique(la_hist_long)) > 1 | length(unique(la_hist_lat)) > 1) & length(la_hist_sal) > 5 )

This new IF statement should be mooved a little further in the code, just after the check for outliers. 

The check for outliers is based on the computation of signal.m.  If there is only 1 data point, signal = 0, so we also need to check that signal_sal>0 before calculationg bad= find(abs(la_hist_sal-mean_sal)/sqrt(signal_sal) >3);


```
% map historical data to float profiles -------------------------
                       
                        % check for outliers
                       
                        mean_sal = mean(la_hist_sal);
                        signal_sal = signal( la_hist_sal ) ;
                       
                        if signal_sal>0
                            bad = find(abs(la_hist_sal-mean_sal)/sqrt(signal_sal) >3);
                           
                            if ~isempty(bad)
                                la_hist_sal(bad)   = [];
                                la_hist_long(bad)  = [];
                                la_hist_lat(bad)   = [];
                                la_hist_dates(bad) = [];
                                la_hist_Z(bad)     = [];
                            end
                        end
                       
                        % use large length scales to map original data
                        % pass NaN for map_age to exclude temporal covariance for large scale mapping
                       
                        % require more than one historical salinity profile with unique position for noise.m; and
                        % require more than five historical salinity profiles to produce realistic mapping error estimates
                        if ( (length(unique(la_hist_long)) > 1 | length(unique(la_hist_lat)) > 1) & length(la_hist_sal) > 5 )


```

**Comment by jlovellcsiro** [comment]
I have installed the new file and confirmed that it works with our problem float. Thanks @cabanesc and Annie!
